# Generated by Django 3.1.3 on 2020-11-26 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201126_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
