# Generated by Django 3.1.3 on 2020-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201127_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing and Accessories', 'Clothing'), ('Electronics and Games', 'Electronics'), ('Other', 'Other'), ('None', ' ')], default='None', max_length=30),
        ),
    ]
