# Generated by Django 3.1.3 on 2020-11-27 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201127_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing and Accessories', 'Clothing And Accessories'), ('Electronics and Games', 'Electronics And Games'), ('Other', 'Other'), ('None', ' ')], default='None', max_length=30),
        ),
    ]
