# Generated by Django 3.1.3 on 2020-11-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201129_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
