# Generated by Django 3.1.3 on 2020-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201129_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Bid'),
        ),
    ]
