# Generated by Django 3.1.3 on 2020-11-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20201130_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='short_description',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
