# Generated by Django 3.1.3 on 2020-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_listing_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='short_description',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
